version: '3.8'

services:
  app:
    image: asheshbh11/freelance-travel:7.0
    container_name: freelance-travel-app
    ports:
      - "8000:8000"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
