version: '3.8'

services:
  app:
    image: travel:latest
    container_name: freelance-travel-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
