version: '3.8'
services:
  redis:
    image: redis:7.0.12
    container_name: freelance-travel-redis
    platform: linux/amd64
    volumes:
      - ./redis_data:/data
    networks:
      - laravel
    ports:
      - "6379:6379"
      
networks:
  laravel:
    driver: bridge