server {
    server_name confirmationtest02.freelancetravel.com www.confirmationtest02.freelancetravel.com;

    # directory should be same as root directory of laravel app
    root /var/www/html;
    index index.php index.html;

    # Forward all requests to PHP-FPM in the container
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP file handling
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000; # Forward requests to PHP-FPM (exposed Docker port)
        fastcgi_index index.php;
        # add public since laravel host serves from public directory
        fastcgi_param SCRIPT_FILENAME $document_root/public/$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/confirmationtest02.freelancetravel.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/confirmationtest02.freelancetravel.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name confirmationtest02.freelancetravel.com www.confirmationtest02.freelancetravel.com;
    return 301 https://$host$request_uri;
}