<?php

if (!defined('ENV_KEY_ACCESS_TOKEN_VALIDITY_PERIOD_IN_MINUTES')) {
    define('ENV_KEY_ACCESS_TOKEN_VALIDITY_PERIOD_IN_MINUTES', 'ACCESS_TOKEN_VALIDITY_PERIOD_IN_MINUTES');
}

if (!defined('ENV_KEY_APP_ENV')) {
    define('ENV_KEY_APP_ENV', 'APP_ENV');
}

if (!defined('ENV_KEY_APP_KEY')) {
    define('ENV_KEY_APP_KEY', 'APP_KEY');
}

if (!defined('ENV_KEY_APP_NAME')) {
    define('ENV_KEY_APP_NAME', 'APP_NAME');
}

if (!defined('ENV_KEY_AUTH_GUARD')) {
    define('ENV_KEY_AUTH_GUARD', 'AUTH_GUARD');
}

if (!defined('ENV_KEY_RATE_LIMIT_PER_MINUTE')) {
    define('ENV_KEY_RATE_LIMIT_PER_MINUTE', 'RATE_LIMIT_PER_MINUTE');
}

if (!defined('ENV_KEY_REFRESH_TOKEN_VALIDITY_PERIOD_IN_MINUTES')) {
    define('ENV_KEY_REFRESH_TOKEN_VALIDITY_PERIOD_IN_MINUTES', 'REFRESH_TOKEN_VALIDITY_PERIOD_IN_MINUTES');
}

if (!defined('ENV_KEY_JWT_TOKEN_ENCRYPT_ALGORITHM')) {
    define('ENV_KEY_JWT_TOKEN_ENCRYPT_ALGORITHM', 'JWT_TOKEN_ENCRYPT_ALGORITHM');
}
