name: Freelance travel deployment

on:
  push:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
      docker_hub_username:
        description: 'Docker hub username'
        required: true
      docker_hub_password:
        description: 'Docker hub password'
        required: true
      docker_hub_repo:
        description: 'Docker hub repository name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Log in to Amazon ECR
    #   run: |
    #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Log in to Docker Hub
      run: |
        echo "${{ github.event.inputs.docker_hub_password }}" | docker login --username ${{ github.event.inputs.docker_hub_username }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd /ft
        export APP_DOCKER_IMAGE_NAME=${{ github.event.inputs.docker_hub_repo }}
        export APP_DOCKER_IMAGE_TAG=${{ github.event.inputs.image_tag }}
        
        # Create .env file from the template
        envsubst < deployment/env.template.txt > .env

        docker build -t ${{ github.event.inputs.docker_hub_repo }}:${{ github.event.inputs.image_tag }} .
        docker push $ECR_REPOSITORY_NAME:${{ github.event.inputs.image_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}  # Also used in deploy step
      run: |
        # Write the RSA private key to a temporary file
        echo "$SSH_PRIVATE_KEY" > ec2_key.pem
        # Set the appropriate permissions for the private key
        chmod 400 ec2_key.pem

        # Add EC2's IP address to known hosts to avoid host key verification issues
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # SSH into the EC2 instance and pull the new Docker image, then restart the services using Docker Compose
        ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
          cd /ft
          docker pull $ECR_REPOSITORY_NAME:${{ github.event.inputs.image_tag }}
          source .env

          # Create docker-compose.yml file from the template
          envsubst < deployment/docker-compose.template.txt > docker-compose.yml

          docker-compose down
          docker-compose up -d
        EOF

    - name: Clean up PEM file
      run: rm -f ec2_key.pem
