name: Freelance travel web deployment

on:
  workflow_dispatch:
    inputs:
      aws-access-key-id: 
        description: 'AWS access key id'
        required: true
      aws-secret-access-key: 
        description: 'AWS secret access key'
        required: true
      aws-session-token: 
        description: 'AWS session token'
        required: true
      github-branch-name:
        description: 'Github repo branch name for web.'
        required: true
      environment:
        description: 'Environment to deploy to (staging or production)'
        required: true
        default: 'staging'

env:
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
  CLARITY_CODE_BLOCK : ${{ vars.CLARITY_CODE_BLOCK }}
  HELP_SCOUT_CODE_BLOCK: ${{ vars.HELP_SCOUT_CODE_BLOCK }}

jobs:
  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on Invalid Environment
        if: ${{ github.event.inputs.environment != 'staging' && github.event.inputs.environment != 'production' }}
        run: |
          echo "Invalid environment: ${{ github.event.inputs.environment }}. Options are 'staging' or 'production."
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: validate-environment
    outputs:
      build-dir: ${{ steps.set-build-dir.outputs.build-dir }}
    steps:
      - name: Set up SSH for Deploy Key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.WEB_REPO_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa

      - name: Checkout Code
        run: |
          git clone --branch ${{ github.event.inputs.github-branch-name }} --single-branch git@github.com:websitetravel/freelance-website.git

      - name: Setup index html
        run: |
          cd freelance-website
          envsubst < public/index.tpl.html > public/index.html

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: |
          npm install
        working-directory: freelance-website

      - name: Build Frontend
        run: npm run build:${{ github.event.inputs.environment }}
        working-directory: freelance-website

      - name: Set Build Directory Output
        id: set-build-dir
        run: echo "::set-output name=build-dir::freelance-website/build"

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ github.event.inputs.aws-secret-access-key }}
          aws-session-token: ${{ github.event.inputs.aws-session-token }}
          aws-region: ap-southeast-2

      - name: Remove all files from S3
        run: aws s3 rm s3://$S3_BUCKET_NAME --recursive --region ap-southeast-2

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ${{ needs.build.outputs.build-dir }} s3://$S3_BUCKET_NAME --delete --region ap-southeast-2

  invalidate-cloudfront:
    runs-on: ubuntu-latest
    needs: deploy-to-s3
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ github.event.inputs.aws-secret-access-key }}
          aws-session-token: ${{ github.event.inputs.aws-session-token }}
          aws-region: ap-southeast-2

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"