name: Freelance travel api deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
      docker_hub_username:
        description: 'Docker hub username'
        required: true
      docker_hub_password:
        description: 'Docker hub password'
        required: true
      docker_hub_repo:
        description: 'Docker hub repository name'
        required: true

env:
      APP_NAME: ${{ vars.APP_NAME }}
      APP_ENV: ${{ vars.APP_ENV }}
      APP_KEY: ${{ vars.APP_KEY }}
      APP_DEBUG: ${{ vars.APP_DEBUG }}
      APP_URL: ${{ vars.APP_URL }}
      APP_PORT: ${{ vars.APP_PORT }}
      API_IP_ADDRESS: ${{ vars.API_IP_ADDRESS }}
      DB_CONNECTION: ${{ vars.DB_CONNECTION }}
      DB_HOST: ${{ vars.DB_IP_ADDRESS }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_DATABASE: ${{ vars.DB_DATABASE }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_PASSWORD_ROOT: ${{ vars.DB_PASSWORD_ROOT }}
      GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
      SSO_TYPE_GOOGLE: ${{ vars.SSO_TYPE_GOOGLE }}
      SSO_TYPE_APPLE: ${{ vars.SSO_TYPE_APPLE }}
      JWT_TOKEN_ENCRYPT_ALGORITHM: ${{ vars.JWT_TOKEN_ENCRYPT_ALGORITHM }}
      ACCESS_TOKEN_VALIDITY_PERIOD_IN_MINUTES: ${{ vars.ACCESS_TOKEN_VALIDITY_PERIOD_IN_MINUTES }}
      REFRESH_TOKEN_VALIDITY_PERIOD_IN_MINUTES: ${{ vars.REFRESH_TOKEN_VALIDITY_PERIOD_IN_MINUTES }}
      APP_DOCKER_IMAGE_NAME: ${{ github.event.inputs.docker_hub_repo }}
      APP_DOCKER_IMAGE_TAG: ${{ github.event.inputs.image_tag }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      APPLE_CLIENT_IDS: ${{ vars.APPLE_CLIENT_IDS }}
      GOOGLE_CLIENT_IDS: ${{ vars.GOOGLE_CLIENT_IDS }}
      APPLE_CLIENT_ID: ${{ vars.APPLE_CLIENT_ID }}
      MAIL_MAILER: ${{ vars.MAIL_MAILER }}
      MAIL_HOST: ${{ vars.MAIL_HOST }}
      MAIL_PORT: ${{ vars.MAIL_PORT }}
      BREVO_MAIL_API_KEY: ${{ vars.BREVO_MAIL_API_KEY }}
      MAIL_ENCRYPTION: ${{ vars.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ vars.MAIL_FROM_ADDRESS }}
      MAIL_FROM_NAME: ${{ vars.APP_NAME }}
      SHARED_TOKEN_AGENT_USERNAME: ${{secrets.SHARED_TOKEN_AGENT_USERNAME}}
      SHARED_TOKEN_AGENT_PASSWORD: ${{secrets.SHARED_TOKEN_AGENT_PASSWORD}}
      TDMS_API_URL: ${{vars.TDMS_API_URL}}
      RETACK_ERROR_LOGGING_URL: ${{vars.RETACK_ERROR_LOGGING_URL}}
      RETACK_ENV_KEY: ${{vars.RETACK_ENV_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .env file
      run: |
        echo "Creating .env file..."
        
        # Create .env file from the template
        envsubst < deployment/env.template.txt > .env

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Log in to Amazon ECR
    #   run: |
    #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Log in to Docker Hub
      run: |
        echo "${{ github.event.inputs.docker_hub_password }}" | docker login --username ${{ github.event.inputs.docker_hub_username }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ github.event.inputs.docker_hub_repo }}:${{ github.event.inputs.image_tag }} .
        docker push $APP_DOCKER_IMAGE_NAME:$APP_DOCKER_IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Deploy api to EC2 instance
      run: |
        # Write the RSA private key to a temporary file
        echo "$SSH_PRIVATE_KEY" > ec2_key.pem
        # Set the appropriate permissions for the private key
        chmod 400 ec2_key.pem

        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh

        # Add EC2's IP address to known hosts to avoid host key verification issues
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Create and Copy docker compose file to EC2 instance
        envsubst < deployment/api-compose.template.txt > api-compose.yml
        scp -i ec2_key.pem api-compose.yml $EC2_USER@$EC2_HOST:~/deploy/api/api-compose.yml

        # SSH into the EC2 instance and pull the new Docker image, then restart the services using Docker Compose
        echo 'Getting into EC2 server'
        ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
          cd ~/deploy/api
          docker-compose -f api-compose.yml down
          docker-compose -f api-compose.yml up -d

          echo "Reloading Nginx"
          sudo systemctl reload nginx
        EOF
